### ISSUE TITLE
why import "C" is required

### ISSUE THREAD

**Issue by suntong** [vladimirvivien/go-plugin-example#2]
Hi Vladimir, 

Thanks for the excellent example of  Go 1.8's plugin. One question, why import "C" is required? 

That `import "C"` doesn't show up in https://tip.golang.org/pkg/plugin/, nor your https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9 or https://github.com/vladimirvivien/go-plugin-example, but in the source code it say, 

> // required

why? thanks!

**Comment by vladimirvivien** [comment]
@suntong 
thank you for asking the question.  When plugins first showed up, that used to be a requirement.  It probably got removed since.  I haven't checked in a while.  If you find that it's not needed, please submit a PR and I will approve.  Thanks again!

**Comment by suntong** [comment]
It is in fact not necessary. Tested.
https://github.com/vladimirvivien/go-plugin-example/pull/3
